version: "3.9"

services:

  redis:
    image: redis:alpine
    volumes:
      - ./data/redis/:/data/

  django-gunicorn:
    build:
      context: ./
      dockerfile: ./Dockerfile
    entrypoint: ./entrypoint.sh
    volumes:
      - ./static/:/usr/src/SpecialRecipe/static/
      - ./media/:/usr/src/SpecialRecipe/media/
      - ./logs/:/usr/src/SpecialRecipe/logs/
    env_file:
      - ./.env
    expose:
      - 8000
    depends_on:
      - redis

  nginx:
    image: nginx:alpine
    volumes:
      - ./static/:/usr/src/SpecialRecipe/static/
      - ./media/:/usr/src/SpecialRecipe/media/
      - ./data/nginx/:/etc/nginx/conf.d/
      - ./data/certbot/conf/:/etc/letsencrypt/
      - ./data/certbot/www/:/var/www/certbot/
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    env_file:
      - ./.env
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django-gunicorn

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf/:/etc/letsencrypt/
      - ./data/certbot/www/:/var/www/certbot/
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  celery:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./logs/:/usr/src/SpecialRecipe/logs/
    command: celery -A core worker -l INFO --logfile logs/celery.log
    env_file:
      - ./.env
    depends_on:
      - django-gunicorn
      - redis
